export const classNameDefault = [
    // Styles of the component
    "w-9",
    "h-3.5",
    "rounded-[7px]",
    "duration-300",
    // Before properties of the component
    "before:content-['']",
    "before:absolute",
    "before:h-8",
    "before:w-8",
    "before:rounded-full",
    "before:top-[-9px]",
    "before:-left-1.5",
    "before:z-[-1]",
    "before:transition-all",
    "before:duration-300",
    // After properties of the component
    "after:content-['']",
    "after:h-5",
    "after:w-5",
    "after:rounded-full",
    "after:absolute",
    "after:top-[-3px]",
    "after:left-0",
    "after:transition-all",
    "after:duration-300",
    // Peer properties of the component
    "peer",
    "peer-checked:before:left-auto",
    "peer-checked:before:-right-1.5",
    "peer-checked:after:left-auto",
    "peer-checked:after:right-0",
    "peer-disabled:before:opacity-0",
];
